services:
  redis-node-1:
    build: ./redis-node-1
    container_name: redis-node-1
    ports:
      - "7001:6379"
      - "17001:16379"
    environment:
      - REDIS_PORT=6379
      - REDIS_CLUSTER_ANNOUNCE_IP=redis-node-1
    networks:
      # network_mode: host
      redis-cluster-net:
        ipv4_address: 172.20.0.2
    volumes:
      - redis-node-1-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node-2:
    build: ./redis-node-2
    container_name: redis-node-2
    ports:
      - "7002:6379"
      - "17002:16379"
    environment:
      - REDIS_PORT=6379
      - REDIS_CLUSTER_ANNOUNCE_IP=redis-node-2
    networks:
      # network_mode: host
      redis-cluster-net:
        ipv4_address: 172.20.0.3
    volumes:
      - redis-node-2-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node-3:
    build: ./redis-node-3
    container_name: redis-node-3
    ports:
      - "7003:6379"
      - "17003:16379"
    environment:
      - REDIS_PORT=6379
      - REDIS_CLUSTER_ANNOUNCE_IP=redis-node-3
    networks:
      # network_mode: host
      redis-cluster-net:
        ipv4_address: 172.20.0.4
    volumes:
      - redis-node-3-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
  
  cluster-init:
    image: redis:7.2-alpine
    container_name: redis-cluster
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
    networks:
      - redis-cluster-net
    volumes:
      - ./cluster-init.sh:/cluster-init.sh
    entrypoint: ["/bin/sh", "/cluster-init.sh"]

networks:
  redis-cluster-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  redis-node-1-data:
  redis-node-2-data:
  redis-node-3-data:



